tasks:

  - source: tasks/hts2ambit_norm.py
    product:
      nb: "{{folder_output}}/hts2ambit_norm.ipynb"
      data: "{{folder_output}}/hts2ambit"

    params:
      folder_input: "{{folder_input}}"
      files_input: "{{files_input}}"
      metadata_template: "{{metadata_template}}"
      filtrate_by_material: "{{filtrate_by_material}}"
      filtrate_by_cells: "{{filtrate_by_cells}}"


  - source: tasks/processed2ambit.py
    product:
      nb: "{{folder_output}}/processed2ambit.ipynb"
      data: "{{folder_output}}/Misvik_substances.nxs"