tasks:

  - source: tasks/ambit_data2HTS_obj.py
    product:
      nb: "products/extract_data.ipynb"
      data_json: "{{folder_output}}/substances_data"
      data_obj: "{{folder_output}}/substances_data_hts"
    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"

  - source: tasks/local_data2HTS_obj.py
    product:
      nb: "products/read_local_hts_obj.ipynb"
      data: "{{folder_output}}/{{config_key}}/substances_data_hts_local"
    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"

#  - source: tasks/nexus.py
#    product:
#      nb: "{{folder_output}}/write_to_nexus.ipynb"
#    params:
#      folder_output: "{{folder_output}}"
#      config_file: "{{config_file}}"
#      config_key: "{{config_key}}"

  - source: tasks/process_hts_obj.py
    product:
      nb: "products/read_process_hts_obj.ipynb"
      data: "{{folder_output}}/{{config_key}}/processed_hts_obj"
    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"


  - source: tasks/metl_df.py
    product:
      nb: "products/test.ipynb"
      data: "{{folder_output}}/{{config_key}}/melted_hts_obj"


#  - source: tasks/processed2ambit.py
#    product:
#      nb: "products/processed2ambit_nb.ipynb"
#      data: "{{folder_output}}/calibrate_substances.nxs"
#      data_json: "{{folder_output}}/result_json"
#    params:
#      config_file: "{{config_file}}"
#      config_key: "{{config_key}}"
#      combine_data_with: "{{combine_data_with}}"


  - source: tasks/tox5_scoring.py
    product:
      nb: "products/tox5_scoring.ipynb"
      data: "{{folder_output}}/tox5_scored_data"
    params:
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"
      combine_data_with: "{{combine_data_with}}"
      combine_w_wo_serum: "{{combine_w_wo_serum}}"


