tasks:

  - source: tasks/extract_data.py
    product:
      nb: "products/extract_data.ipynb"
      data: "{{folder_output}}/substances_data"

    params:
      folder_output: "{{folder_output}}"
      enm_api_url: "{{enm_api_url}}"
      enm_api_key: "{{enm_api_key}}"
      query: "{{query}}"
      db: "{{db}}"

  - source: tasks/nexus.py
    product:
      nb: "{{folder_output}}/write_to_nexus.ipynb"
    params:
      folder_output: "{{folder_output}}"
      query: "{{query}}"

  - source: tasks/ambit2hts.py
    product:
      nb: "products/ambit2hts_tox5.ipynb"
      data: "{{folder_output}}/substances_hts_obj"
    params:
      folder_output: "{{folder_output}}"

  - source: tasks/process_hts_obj_test.py
    product:
      nb: "products/read_process_hts_obj.ipynb"
    params:
      folder_output: "{{folder_output}}"
      folder_input: "{{folder_input}}"
      files_input: "{{files_input}}"
      metadata_templates: "{{metadata_templates}}"
