tasks:

  - source: tasks/ambit_data2HTS_obj.py
    product:
      nb: "products/extract_data.ipynb"
      data_json: "{{folder_output}}/substances_data"
      data_obj: "{{folder_output}}/substances_data_hts"

    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"

  - source: tasks/local_data2HTS_obj.py
    product:
      nb: "products/read_local_hts_obj.ipynb"
      data: "{{folder_output}}/substances_data_hts_local"
    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"

#  - source: tasks/nexus.py
#    product:
#      nb: "{{folder_output}}/write_to_nexus.ipynb"
#    params:
#      folder_output: "{{folder_output}}"
#      query: "{{query}}"
#
#  - source: tasks/ambit2hts.py
#    product:
#      nb: "products/ambit2hts_tox5.ipynb"
#      data: "{{folder_output}}/substances_hts_obj"
#    params:
#      folder_output: "{{folder_output}}"
#
  - source: tasks/process_hts_obj.py
    product:
      nb: "products/read_process_hts_obj.ipynb"
      data: "{{folder_output}}/processed_hts_obj"
    params:
      folder_output: "{{folder_output}}"
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"

#
  - source: tasks/metl_df.py
    product:
      nb: "products/test.ipynb"
      data: "{{folder_output}}/melted_hts_obj"
#
  - source: tasks/processed2ambit.py
    product:
      nb: "products/processed2ambit_nb.ipynb"
      data: "{{folder_output}}/Calibrate_substances_2.nxs"
    params:
      config_file: "{{config_file}}"
      config_key: "{{config_key}}"
#
#
#  - source: tasks/tox5_scoring.py
#    product:
#      nb: "products/tox5_scoring.ipynb"
#      data: "{{folder_output}}/ready_data"
